import { Poppins } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/auth.context";
import { AssessmentProvider } from "./context/assessments.context";
import { NeedsProvider } from "./context/needs.context";
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NeedsProvider>
        <AssessmentProvider>
        <AuthProvider>
        {children}
        </AuthProvider>
        </AssessmentProvider>
        </NeedsProvider>
      </body>
    </html>
  );
}

